name: amcrest2mqtt
version: 2022.3.0
slug: amcrest2mqtt-addon
description: A Home Assistant addon for amcrest2mqtt
url: https://github.com/ikifar2012/amcrest2mqtt-addon/blob/master/README.md
arch:
- armhf
- armv7
- aarch64
- amd64
- i386
image: ikifar/amcrest2mqtt-addon-{arch}
startup: services
boot: auto
map:
- ssl:ro
services:
- mqtt:want
options:
  amcrest_host: ''
  amcrest_port: '80'
  amcrest_username: 'admin'
  amcrest_password: ''
  storage_poll_interval: '3600'
  device_name: ''
  home_assistant: true
  home_assistant_prefix: ''
schema:
  amcrest_host: str
  amcrest_port: int
  amcrest_username: str
  amcrest_password: str
  storage_poll_interval: int
  device_name: str
  home_assistant: bool
  home_assistant_prefix: str